/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Decimal as Decimal$ } from "../../types";
import { DataType, DataType$ } from "./datatype";
import { DirectCostLineItem, DirectCostLineItem$ } from "./directcostlineitem";
import { Metadata, Metadata$ } from "./metadata";
import { PaymentAllocationPayment, PaymentAllocationPayment$ } from "./paymentallocationpayment";
import { PushOperationChange, PushOperationChange$ } from "./pushoperationchange";
import { PushOperationStatus, PushOperationStatus$ } from "./pushoperationstatus";
import { SupplementalData, SupplementalData$ } from "./supplementaldata";
import { Validation, Validation$ } from "./validation";
import * as z from "zod";

/**
 * Allowed name of the 'dataType'.
 */
export enum CreateDirectCostResponseDataType {
    Customers = "customers",
    Suppliers = "suppliers",
}

/**
 * A customer or supplier associated with the direct cost.
 */
export type CreateDirectCostResponseContactReference = {
    /**
     * Allowed name of the 'dataType'.
     */
    dataType?: CreateDirectCostResponseDataType | null | undefined;
    /**
     * Unique identifier for a customer or supplier.
     */
    id: string;
};

export type CreateDirectCostResponseAllocation = {
    /**
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>. Date and time fields are formatted as strings; for example:
     *
     * @remarks
     *
     * ```
     * 2020-10-08T22:40:50Z
     * 2021-01-01T00:00:00
     * ```
     *
     *
     *
     * When syncing data that contains `DateTime` fields from Codat, make sure you support the following cases when reading time information:
     *
     * - Coordinated Universal Time (UTC): `2021-11-15T06:00:00Z`
     * - Unqualified local time: `2021-11-15T01:00:00`
     * - UTC time offsets: `2021-11-15T01:00:00-05:00`
     *
     * > Time zones
     * >
     * > Not all dates from Codat will contain information about time zones.
     * > Where it is not available from the underlying platform, Codat will return these as times local to the business whose data has been synced.
     */
    allocatedOnDate?: string | undefined;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     *
     * @remarks
     *
     * ## Unknown currencies
     *
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction.
     *
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     */
    currency?: string | undefined;
    /**
     * Rate to convert the total amount of the payment into the base currency for the company at the time of the payment.
     *
     * @remarks
     *
     * Currency rates in Codat are implemented as the multiple of foreign currency units to each base currency unit.
     *
     * It is not possible to perform the currency conversion with two or more non-base currencies participating in the transaction. For example, if a company's base currency is USD, and it has a bill issued in EUR, then the bill payment must happen in USD or EUR.
     *
     * Where the currency rate is provided by the underlying accounting platform, it will be available from Codat with the same precision (up to a maximum of 9 decimal places).
     *
     * For accounting platforms which do not provide an explicit currency rate, it is calculated as `baseCurrency / foreignCurrency` and will be returned to 9 decimal places.
     *
     * ## Examples with base currency of GBP
     *
     * | Foreign Currency | Foreign Amount | Currency Rate | Base Currency Amount (GBP) |
     * | :--------------- | :------------- | :------------ | :------------------------- |
     * | **USD**          | $20            | 0.781         | £15.62                     |
     * | **EUR**          | €20            | 0.885         | £17.70                     |
     * | **RUB**          | ₽20            | 0.011         | £0.22                      |
     *
     * ## Examples with base currency of USD
     *
     * | Foreign Currency | Foreign Amount | Currency Rate | Base Currency Amount (USD) |
     * | :--------------- | :------------- | :------------ | :------------------------- |
     * | **GBP**          | £20            | 1.277         | $25.54                     |
     * | **EUR**          | €20            | 1.134         | $22.68                     |
     * | **RUB**          | ₽20            | 0.015         | $0.30                      |
     *
     *
     * ### Integration-specific details
     *
     * | Integration       | Scenario                                        | System behavior                                                                                                                                                      |
     * |-------------------|-------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     * | QuickBooks Online | Transaction currency differs from base currency | If currency rate value is left `null`, a rate of 1 will be used by QBO by default. To override this, include the required currency rate in the expense transaction.  |
     */
    currencyRate?: Decimal$ | number | null | undefined;
    /**
     * The total amount that has been allocated.
     */
    totalAmount?: Decimal$ | number | undefined;
};

export type CreateDirectCostResponseAccountingPaymentAllocation = {
    allocation: CreateDirectCostResponseAllocation;
    payment: PaymentAllocationPayment;
};

/**
 * > **Language tip:** Direct costs may also be referred to as **Spend transactions**, **Spend money transactions**, or **Payments** in various accounting platforms.
 *
 * @remarks
 *
 * > View the coverage for direct costs in the <a className="external" href="https://knowledge.codat.io/supported-features/accounting?view=tab-by-data-type&dataType=directCosts" target="_blank">Data coverage explorer</a>.
 *
 * ## Overview
 *
 * Direct costs are the expenses associated with a business' operations. For example, purchases of raw materials and service fees are considered direct costs.
 *
 * Direct costs include:
 *   * Purchasing an item and paying it off at the point of the purchase
 *   * Receiving cash from a refunded item if the refund is made by the supplier
 *   * Withdrawing money from a bank account
 *   * Writing a cheque
 *
 * Direct costs is a child data type of [account transactions](https://docs.codat.io/accounting-api#/schemas/AccountTransaction).
 *
 * @deprecated class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export type AccountingDirectCost = {
    /**
     * A customer or supplier associated with the direct cost.
     */
    contactRef?: CreateDirectCostResponseContactReference | undefined;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     *
     * @remarks
     *
     * ## Unknown currencies
     *
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction.
     *
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     */
    currency: string;
    /**
     * Rate to convert the total amount of the payment into the base currency for the company at the time of the payment.
     *
     * @remarks
     *
     * Currency rates in Codat are implemented as the multiple of foreign currency units to each base currency unit.
     *
     * It is not possible to perform the currency conversion with two or more non-base currencies participating in the transaction. For example, if a company's base currency is USD, and it has a bill issued in EUR, then the bill payment must happen in USD or EUR.
     *
     * Where the currency rate is provided by the underlying accounting platform, it will be available from Codat with the same precision (up to a maximum of 9 decimal places).
     *
     * For accounting platforms which do not provide an explicit currency rate, it is calculated as `baseCurrency / foreignCurrency` and will be returned to 9 decimal places.
     *
     * ## Examples with base currency of GBP
     *
     * | Foreign Currency | Foreign Amount | Currency Rate | Base Currency Amount (GBP) |
     * | :--------------- | :------------- | :------------ | :------------------------- |
     * | **USD**          | $20            | 0.781         | £15.62                     |
     * | **EUR**          | €20            | 0.885         | £17.70                     |
     * | **RUB**          | ₽20            | 0.011         | £0.22                      |
     *
     * ## Examples with base currency of USD
     *
     * | Foreign Currency | Foreign Amount | Currency Rate | Base Currency Amount (USD) |
     * | :--------------- | :------------- | :------------ | :------------------------- |
     * | **GBP**          | £20            | 1.277         | $25.54                     |
     * | **EUR**          | €20            | 1.134         | $22.68                     |
     * | **RUB**          | ₽20            | 0.015         | $0.30                      |
     *
     *
     * ### Integration-specific details
     *
     * | Integration       | Scenario                                        | System behavior                                                                                                                                                      |
     * |-------------------|-------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     * | QuickBooks Online | Transaction currency differs from base currency | If currency rate value is left `null`, a rate of 1 will be used by QBO by default. To override this, include the required currency rate in the expense transaction.  |
     */
    currencyRate?: Decimal$ | number | null | undefined;
    /**
     * Identifier of the direct cost, unique for the company.
     */
    id?: string | undefined;
    /**
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>. Date and time fields are formatted as strings; for example:
     *
     * @remarks
     *
     * ```
     * 2020-10-08T22:40:50Z
     * 2021-01-01T00:00:00
     * ```
     *
     *
     *
     * When syncing data that contains `DateTime` fields from Codat, make sure you support the following cases when reading time information:
     *
     * - Coordinated Universal Time (UTC): `2021-11-15T06:00:00Z`
     * - Unqualified local time: `2021-11-15T01:00:00`
     * - UTC time offsets: `2021-11-15T01:00:00-05:00`
     *
     * > Time zones
     * >
     * > Not all dates from Codat will contain information about time zones.
     * > Where it is not available from the underlying platform, Codat will return these as times local to the business whose data has been synced.
     */
    issueDate: string;
    /**
     * An array of line items.
     */
    lineItems: Array<DirectCostLineItem>;
    metadata?: Metadata | undefined;
    modifiedDate?: string | undefined;
    /**
     * A note attached to the direct cost.
     */
    note?: string | null | undefined;
    /**
     * An array of payment allocations.
     */
    paymentAllocations: Array<CreateDirectCostResponseAccountingPaymentAllocation>;
    /**
     * User-friendly reference for the direct cost.
     */
    reference?: string | null | undefined;
    sourceModifiedDate?: string | undefined;
    /**
     * The total amount of the direct costs, excluding any taxes.
     */
    subTotal: Decimal$ | number;
    /**
     * Supplemental data is additional data you can include in our standard data types.
     *
     * @remarks
     *
     * It is referenced as a configured dynamic key value pair that is unique to the accounting platform. [Learn more](https://docs.codat.io/using-the-api/supplemental-data/overview) about supplemental data.
     */
    supplementalData?: SupplementalData | undefined;
    /**
     * The total amount of tax on the direct costs.
     */
    taxAmount: Decimal$ | number;
    /**
     * The amount of the direct costs, inclusive of tax.
     */
    totalAmount: Decimal$ | number;
};

export type CreateDirectCostResponse = {
    /**
     * Contains a single entry that communicates which record has changed and the manner in which it changed.
     */
    changes?: Array<PushOperationChange> | null | undefined;
    /**
     * Unique identifier for your SMB in Codat.
     */
    companyId: string;
    /**
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>. Date and time fields are formatted as strings; for example:
     *
     * @remarks
     *
     * ```
     * 2020-10-08T22:40:50Z
     * 2021-01-01T00:00:00
     * ```
     *
     *
     *
     * When syncing data that contains `DateTime` fields from Codat, make sure you support the following cases when reading time information:
     *
     * - Coordinated Universal Time (UTC): `2021-11-15T06:00:00Z`
     * - Unqualified local time: `2021-11-15T01:00:00`
     * - UTC time offsets: `2021-11-15T01:00:00-05:00`
     *
     * > Time zones
     * >
     * > Not all dates from Codat will contain information about time zones.
     * > Where it is not available from the underlying platform, Codat will return these as times local to the business whose data has been synced.
     */
    completedOnUtc?: string | undefined;
    data?: AccountingDirectCost | null | undefined;
    /**
     * Unique identifier for a company's data connection.
     */
    dataConnectionKey: string;
    /**
     * Available data types
     */
    dataType?: DataType | undefined;
    /**
     * A message about the error.
     */
    errorMessage?: string | null | undefined;
    /**
     * A unique identifier generated by Codat to represent this single push operation. This identifier can be used to track the status of the push, and should be persisted.
     */
    pushOperationKey: string;
    /**
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>. Date and time fields are formatted as strings; for example:
     *
     * @remarks
     *
     * ```
     * 2020-10-08T22:40:50Z
     * 2021-01-01T00:00:00
     * ```
     *
     *
     *
     * When syncing data that contains `DateTime` fields from Codat, make sure you support the following cases when reading time information:
     *
     * - Coordinated Universal Time (UTC): `2021-11-15T06:00:00Z`
     * - Unqualified local time: `2021-11-15T01:00:00`
     * - UTC time offsets: `2021-11-15T01:00:00-05:00`
     *
     * > Time zones
     * >
     * > Not all dates from Codat will contain information about time zones.
     * > Where it is not available from the underlying platform, Codat will return these as times local to the business whose data has been synced.
     */
    requestedOnUtc: string;
    /**
     * The current status of the push operation.
     */
    status: PushOperationStatus;
    /**
     * Push status code.
     */
    statusCode: number;
    /**
     * Number of minutes the push operation must complete within before it times out.
     */
    timeoutInMinutes?: number | null | undefined;
    /**
     * Number of seconds the push operation must complete within before it times out.
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    timeoutInSeconds?: number | null | undefined;
    /**
     * A human-readable object describing validation decisions Codat has made when pushing data into the platform. If a push has failed because of validation errors, they will be detailed here.
     */
    validation?: Validation | undefined;
};

/** @internal */
export const CreateDirectCostResponseDataType$ = z.nativeEnum(CreateDirectCostResponseDataType);

/** @internal */
export namespace CreateDirectCostResponseContactReference$ {
    export type Inbound = {
        dataType?: CreateDirectCostResponseDataType | null | undefined;
        id: string;
    };

    export const inboundSchema: z.ZodType<
        CreateDirectCostResponseContactReference,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            dataType: z.nullable(CreateDirectCostResponseDataType$).optional(),
            id: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.dataType === undefined ? null : { dataType: v.dataType }),
                id: v.id,
            };
        });

    export type Outbound = {
        dataType?: CreateDirectCostResponseDataType | null | undefined;
        id: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateDirectCostResponseContactReference
    > = z
        .object({
            dataType: z.nullable(CreateDirectCostResponseDataType$).optional(),
            id: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.dataType === undefined ? null : { dataType: v.dataType }),
                id: v.id,
            };
        });
}

/** @internal */
export namespace CreateDirectCostResponseAllocation$ {
    export type Inbound = {
        allocatedOnDate?: string | undefined;
        currency?: string | undefined;
        currencyRate?: number | null | undefined;
        totalAmount?: number | undefined;
    };

    export const inboundSchema: z.ZodType<
        CreateDirectCostResponseAllocation,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            allocatedOnDate: z.string().optional(),
            currency: z.string().optional(),
            currencyRate: z.nullable(z.number().transform((v) => new Decimal$(v))).optional(),
            totalAmount: z
                .number()
                .transform((v) => new Decimal$(v))
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.allocatedOnDate === undefined
                    ? null
                    : { allocatedOnDate: v.allocatedOnDate }),
                ...(v.currency === undefined ? null : { currency: v.currency }),
                ...(v.currencyRate === undefined ? null : { currencyRate: v.currencyRate }),
                ...(v.totalAmount === undefined ? null : { totalAmount: v.totalAmount }),
            };
        });

    export type Outbound = {
        allocatedOnDate?: string | undefined;
        currency?: string | undefined;
        currencyRate?: number | null | undefined;
        totalAmount?: number | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateDirectCostResponseAllocation
    > = z
        .object({
            allocatedOnDate: z.string().optional(),
            currency: z.string().optional(),
            currencyRate: z
                .nullable(
                    z
                        .union([z.instanceof(Decimal$), z.number()])
                        .transform((v) => (typeof v === "number" ? v : v.toNumber()))
                )
                .optional(),
            totalAmount: z
                .union([z.instanceof(Decimal$), z.number()])
                .transform((v) => (typeof v === "number" ? v : v.toNumber()))
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.allocatedOnDate === undefined
                    ? null
                    : { allocatedOnDate: v.allocatedOnDate }),
                ...(v.currency === undefined ? null : { currency: v.currency }),
                ...(v.currencyRate === undefined ? null : { currencyRate: v.currencyRate }),
                ...(v.totalAmount === undefined ? null : { totalAmount: v.totalAmount }),
            };
        });
}

/** @internal */
export namespace CreateDirectCostResponseAccountingPaymentAllocation$ {
    export type Inbound = {
        allocation: CreateDirectCostResponseAllocation$.Inbound;
        payment: PaymentAllocationPayment$.Inbound;
    };

    export const inboundSchema: z.ZodType<
        CreateDirectCostResponseAccountingPaymentAllocation,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            allocation: z.lazy(() => CreateDirectCostResponseAllocation$.inboundSchema),
            payment: PaymentAllocationPayment$.inboundSchema,
        })
        .transform((v) => {
            return {
                allocation: v.allocation,
                payment: v.payment,
            };
        });

    export type Outbound = {
        allocation: CreateDirectCostResponseAllocation$.Outbound;
        payment: PaymentAllocationPayment$.Outbound;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateDirectCostResponseAccountingPaymentAllocation
    > = z
        .object({
            allocation: z.lazy(() => CreateDirectCostResponseAllocation$.outboundSchema),
            payment: PaymentAllocationPayment$.outboundSchema,
        })
        .transform((v) => {
            return {
                allocation: v.allocation,
                payment: v.payment,
            };
        });
}

/** @internal */
export namespace AccountingDirectCost$ {
    export type Inbound = {
        contactRef?: CreateDirectCostResponseContactReference$.Inbound | undefined;
        currency: string;
        currencyRate?: number | null | undefined;
        id?: string | undefined;
        issueDate: string;
        lineItems: Array<DirectCostLineItem$.Inbound>;
        metadata?: Metadata$.Inbound | undefined;
        modifiedDate?: string | undefined;
        note?: string | null | undefined;
        paymentAllocations: Array<CreateDirectCostResponseAccountingPaymentAllocation$.Inbound>;
        reference?: string | null | undefined;
        sourceModifiedDate?: string | undefined;
        subTotal: number;
        supplementalData?: SupplementalData$.Inbound | undefined;
        taxAmount: number;
        totalAmount: number;
    };

    export const inboundSchema: z.ZodType<AccountingDirectCost, z.ZodTypeDef, Inbound> = z
        .object({
            contactRef: z
                .lazy(() => CreateDirectCostResponseContactReference$.inboundSchema)
                .optional(),
            currency: z.string(),
            currencyRate: z.nullable(z.number().transform((v) => new Decimal$(v))).optional(),
            id: z.string().optional(),
            issueDate: z.string(),
            lineItems: z.array(DirectCostLineItem$.inboundSchema),
            metadata: Metadata$.inboundSchema.optional(),
            modifiedDate: z.string().optional(),
            note: z.nullable(z.string()).optional(),
            paymentAllocations: z.array(
                z.lazy(() => CreateDirectCostResponseAccountingPaymentAllocation$.inboundSchema)
            ),
            reference: z.nullable(z.string()).optional(),
            sourceModifiedDate: z.string().optional(),
            subTotal: z.number().transform((v) => new Decimal$(v)),
            supplementalData: SupplementalData$.inboundSchema.optional(),
            taxAmount: z.number().transform((v) => new Decimal$(v)),
            totalAmount: z.number().transform((v) => new Decimal$(v)),
        })
        .transform((v) => {
            return {
                ...(v.contactRef === undefined ? null : { contactRef: v.contactRef }),
                currency: v.currency,
                ...(v.currencyRate === undefined ? null : { currencyRate: v.currencyRate }),
                ...(v.id === undefined ? null : { id: v.id }),
                issueDate: v.issueDate,
                lineItems: v.lineItems,
                ...(v.metadata === undefined ? null : { metadata: v.metadata }),
                ...(v.modifiedDate === undefined ? null : { modifiedDate: v.modifiedDate }),
                ...(v.note === undefined ? null : { note: v.note }),
                paymentAllocations: v.paymentAllocations,
                ...(v.reference === undefined ? null : { reference: v.reference }),
                ...(v.sourceModifiedDate === undefined
                    ? null
                    : { sourceModifiedDate: v.sourceModifiedDate }),
                subTotal: v.subTotal,
                ...(v.supplementalData === undefined
                    ? null
                    : { supplementalData: v.supplementalData }),
                taxAmount: v.taxAmount,
                totalAmount: v.totalAmount,
            };
        });

    export type Outbound = {
        contactRef?: CreateDirectCostResponseContactReference$.Outbound | undefined;
        currency: string;
        currencyRate?: number | null | undefined;
        id?: string | undefined;
        issueDate: string;
        lineItems: Array<DirectCostLineItem$.Outbound>;
        metadata?: Metadata$.Outbound | undefined;
        modifiedDate?: string | undefined;
        note?: string | null | undefined;
        paymentAllocations: Array<CreateDirectCostResponseAccountingPaymentAllocation$.Outbound>;
        reference?: string | null | undefined;
        sourceModifiedDate?: string | undefined;
        subTotal: number;
        supplementalData?: SupplementalData$.Outbound | undefined;
        taxAmount: number;
        totalAmount: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AccountingDirectCost> = z
        .object({
            contactRef: z
                .lazy(() => CreateDirectCostResponseContactReference$.outboundSchema)
                .optional(),
            currency: z.string(),
            currencyRate: z
                .nullable(
                    z
                        .union([z.instanceof(Decimal$), z.number()])
                        .transform((v) => (typeof v === "number" ? v : v.toNumber()))
                )
                .optional(),
            id: z.string().optional(),
            issueDate: z.string(),
            lineItems: z.array(DirectCostLineItem$.outboundSchema),
            metadata: Metadata$.outboundSchema.optional(),
            modifiedDate: z.string().optional(),
            note: z.nullable(z.string()).optional(),
            paymentAllocations: z.array(
                z.lazy(() => CreateDirectCostResponseAccountingPaymentAllocation$.outboundSchema)
            ),
            reference: z.nullable(z.string()).optional(),
            sourceModifiedDate: z.string().optional(),
            subTotal: z
                .union([z.instanceof(Decimal$), z.number()])
                .transform((v) => (typeof v === "number" ? v : v.toNumber())),
            supplementalData: SupplementalData$.outboundSchema.optional(),
            taxAmount: z
                .union([z.instanceof(Decimal$), z.number()])
                .transform((v) => (typeof v === "number" ? v : v.toNumber())),
            totalAmount: z
                .union([z.instanceof(Decimal$), z.number()])
                .transform((v) => (typeof v === "number" ? v : v.toNumber())),
        })
        .transform((v) => {
            return {
                ...(v.contactRef === undefined ? null : { contactRef: v.contactRef }),
                currency: v.currency,
                ...(v.currencyRate === undefined ? null : { currencyRate: v.currencyRate }),
                ...(v.id === undefined ? null : { id: v.id }),
                issueDate: v.issueDate,
                lineItems: v.lineItems,
                ...(v.metadata === undefined ? null : { metadata: v.metadata }),
                ...(v.modifiedDate === undefined ? null : { modifiedDate: v.modifiedDate }),
                ...(v.note === undefined ? null : { note: v.note }),
                paymentAllocations: v.paymentAllocations,
                ...(v.reference === undefined ? null : { reference: v.reference }),
                ...(v.sourceModifiedDate === undefined
                    ? null
                    : { sourceModifiedDate: v.sourceModifiedDate }),
                subTotal: v.subTotal,
                ...(v.supplementalData === undefined
                    ? null
                    : { supplementalData: v.supplementalData }),
                taxAmount: v.taxAmount,
                totalAmount: v.totalAmount,
            };
        });
}

/** @internal */
export namespace CreateDirectCostResponse$ {
    export type Inbound = {
        changes?: Array<PushOperationChange$.Inbound> | null | undefined;
        companyId: string;
        completedOnUtc?: string | undefined;
        data?: AccountingDirectCost$.Inbound | null | undefined;
        dataConnectionKey: string;
        dataType?: DataType | undefined;
        errorMessage?: string | null | undefined;
        pushOperationKey: string;
        requestedOnUtc: string;
        status: PushOperationStatus;
        statusCode: number;
        timeoutInMinutes?: number | null | undefined;
        timeoutInSeconds?: number | null | undefined;
        validation?: Validation$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreateDirectCostResponse, z.ZodTypeDef, Inbound> = z
        .object({
            changes: z.nullable(z.array(PushOperationChange$.inboundSchema)).optional(),
            companyId: z.string(),
            completedOnUtc: z.string().optional(),
            data: z.nullable(z.lazy(() => AccountingDirectCost$.inboundSchema)).optional(),
            dataConnectionKey: z.string(),
            dataType: DataType$.optional(),
            errorMessage: z.nullable(z.string()).optional(),
            pushOperationKey: z.string(),
            requestedOnUtc: z.string(),
            status: PushOperationStatus$,
            statusCode: z.number().int(),
            timeoutInMinutes: z.nullable(z.number().int()).optional(),
            timeoutInSeconds: z.nullable(z.number().int()).optional(),
            validation: Validation$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.changes === undefined ? null : { changes: v.changes }),
                companyId: v.companyId,
                ...(v.completedOnUtc === undefined ? null : { completedOnUtc: v.completedOnUtc }),
                ...(v.data === undefined ? null : { data: v.data }),
                dataConnectionKey: v.dataConnectionKey,
                ...(v.dataType === undefined ? null : { dataType: v.dataType }),
                ...(v.errorMessage === undefined ? null : { errorMessage: v.errorMessage }),
                pushOperationKey: v.pushOperationKey,
                requestedOnUtc: v.requestedOnUtc,
                status: v.status,
                statusCode: v.statusCode,
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
                ...(v.timeoutInSeconds === undefined
                    ? null
                    : { timeoutInSeconds: v.timeoutInSeconds }),
                ...(v.validation === undefined ? null : { validation: v.validation }),
            };
        });

    export type Outbound = {
        changes?: Array<PushOperationChange$.Outbound> | null | undefined;
        companyId: string;
        completedOnUtc?: string | undefined;
        data?: AccountingDirectCost$.Outbound | null | undefined;
        dataConnectionKey: string;
        dataType?: DataType | undefined;
        errorMessage?: string | null | undefined;
        pushOperationKey: string;
        requestedOnUtc: string;
        status: PushOperationStatus;
        statusCode: number;
        timeoutInMinutes?: number | null | undefined;
        timeoutInSeconds?: number | null | undefined;
        validation?: Validation$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateDirectCostResponse> = z
        .object({
            changes: z.nullable(z.array(PushOperationChange$.outboundSchema)).optional(),
            companyId: z.string(),
            completedOnUtc: z.string().optional(),
            data: z.nullable(z.lazy(() => AccountingDirectCost$.outboundSchema)).optional(),
            dataConnectionKey: z.string(),
            dataType: DataType$.optional(),
            errorMessage: z.nullable(z.string()).optional(),
            pushOperationKey: z.string(),
            requestedOnUtc: z.string(),
            status: PushOperationStatus$,
            statusCode: z.number().int(),
            timeoutInMinutes: z.nullable(z.number().int()).optional(),
            timeoutInSeconds: z.nullable(z.number().int()).optional(),
            validation: Validation$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.changes === undefined ? null : { changes: v.changes }),
                companyId: v.companyId,
                ...(v.completedOnUtc === undefined ? null : { completedOnUtc: v.completedOnUtc }),
                ...(v.data === undefined ? null : { data: v.data }),
                dataConnectionKey: v.dataConnectionKey,
                ...(v.dataType === undefined ? null : { dataType: v.dataType }),
                ...(v.errorMessage === undefined ? null : { errorMessage: v.errorMessage }),
                pushOperationKey: v.pushOperationKey,
                requestedOnUtc: v.requestedOnUtc,
                status: v.status,
                statusCode: v.statusCode,
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
                ...(v.timeoutInSeconds === undefined
                    ? null
                    : { timeoutInSeconds: v.timeoutInSeconds }),
                ...(v.validation === undefined ? null : { validation: v.validation }),
            };
        });
}
