/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Decimal as Decimal$ } from "../../types";
import * as z from "zod";

export type AgedOutstandingAmountDetail = {
    /**
     * Name of data type with outstanding amount for given period.
     */
    name?: string | undefined;
    /**
     * The amount outstanding.
     */
    amount?: Decimal$ | number | undefined;
};

/** @internal */
export namespace AgedOutstandingAmountDetail$ {
    export type Inbound = {
        name?: string | undefined;
        amount?: number | undefined;
    };

    export const inboundSchema: z.ZodType<AgedOutstandingAmountDetail, z.ZodTypeDef, Inbound> = z
        .object({
            name: z.string().optional(),
            amount: z
                .number()
                .transform((v) => new Decimal$(v))
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.amount === undefined ? null : { amount: v.amount }),
            };
        });

    export type Outbound = {
        name?: string | undefined;
        amount?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AgedOutstandingAmountDetail> = z
        .object({
            name: z.string().optional(),
            amount: z
                .union([z.instanceof(Decimal$), z.number()])
                .transform((v) => (typeof v === "number" ? v : v.toNumber()))
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.amount === undefined ? null : { amount: v.amount }),
            };
        });
}
