/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Decimal as Decimal$ } from "../../types";
import { AccountRef, AccountRef$ } from "./accountref";
import { TrackingRecordRef, TrackingRecordRef$ } from "./trackingrecordref";
import * as z from "zod";

/**
 * List of record refs associated with the tracking information for the line (eg to a Tracking Category, or customer etc.)
 */
export type JournalLineTracking = {
    recordRefs?: Array<TrackingRecordRef> | null | undefined;
};

export type JournalLine = {
    /**
     * Description of the journal line item.
     */
    description?: string | null | undefined;
    /**
     * Amount for the journal line. Debit entries are considered positive, and credit entries are considered negative.
     */
    netAmount: Decimal$ | number;
    /**
     * Currency for the journal line item.
     */
    currency?: string | null | undefined;
    /**
     * Data types that reference an account, for example bill and invoice line items, use an accountRef that includes the ID and name of the linked account.
     */
    accountRef?: AccountRef | undefined;
    /**
     * List of record refs associated with the tracking information for the line (eg to a Tracking Category, or customer etc.)
     */
    tracking?: JournalLineTracking | undefined;
};

/** @internal */
export namespace JournalLineTracking$ {
    export type Inbound = {
        recordRefs?: Array<TrackingRecordRef$.Inbound> | null | undefined;
    };

    export const inboundSchema: z.ZodType<JournalLineTracking, z.ZodTypeDef, Inbound> = z
        .object({
            recordRefs: z.nullable(z.array(TrackingRecordRef$.inboundSchema)).optional(),
        })
        .transform((v) => {
            return {
                ...(v.recordRefs === undefined ? null : { recordRefs: v.recordRefs }),
            };
        });

    export type Outbound = {
        recordRefs?: Array<TrackingRecordRef$.Outbound> | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, JournalLineTracking> = z
        .object({
            recordRefs: z.nullable(z.array(TrackingRecordRef$.outboundSchema)).optional(),
        })
        .transform((v) => {
            return {
                ...(v.recordRefs === undefined ? null : { recordRefs: v.recordRefs }),
            };
        });
}

/** @internal */
export namespace JournalLine$ {
    export type Inbound = {
        description?: string | null | undefined;
        netAmount: number;
        currency?: string | null | undefined;
        accountRef?: AccountRef$.Inbound | undefined;
        tracking?: JournalLineTracking$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<JournalLine, z.ZodTypeDef, Inbound> = z
        .object({
            description: z.nullable(z.string()).optional(),
            netAmount: z.number().transform((v) => new Decimal$(v)),
            currency: z.nullable(z.string()).optional(),
            accountRef: AccountRef$.inboundSchema.optional(),
            tracking: z.lazy(() => JournalLineTracking$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.description === undefined ? null : { description: v.description }),
                netAmount: v.netAmount,
                ...(v.currency === undefined ? null : { currency: v.currency }),
                ...(v.accountRef === undefined ? null : { accountRef: v.accountRef }),
                ...(v.tracking === undefined ? null : { tracking: v.tracking }),
            };
        });

    export type Outbound = {
        description?: string | null | undefined;
        netAmount: number;
        currency?: string | null | undefined;
        accountRef?: AccountRef$.Outbound | undefined;
        tracking?: JournalLineTracking$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, JournalLine> = z
        .object({
            description: z.nullable(z.string()).optional(),
            netAmount: z
                .union([z.instanceof(Decimal$), z.number()])
                .transform((v) => (typeof v === "number" ? v : v.toNumber())),
            currency: z.nullable(z.string()).optional(),
            accountRef: AccountRef$.outboundSchema.optional(),
            tracking: z.lazy(() => JournalLineTracking$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.description === undefined ? null : { description: v.description }),
                netAmount: v.netAmount,
                ...(v.currency === undefined ? null : { currency: v.currency }),
                ...(v.accountRef === undefined ? null : { accountRef: v.accountRef }),
                ...(v.tracking === undefined ? null : { tracking: v.tracking }),
            };
        });
}
