/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { BankAccounts } from "./bankaccounts";
import { BankTransactions } from "./banktransactions";
import { CreateOperations } from "./createoperations";
import { DirectCosts } from "./directcosts";
import { LendingLoanWritebackAccounts } from "./lendingloanwritebackaccounts";
import { LendingPayments } from "./lendingpayments";
import { LendingSuppliers } from "./lendingsuppliers";
import { SDKConfiguration } from "./sdk";
import { Transfers } from "./transfers";

export class LoanWriteback {
    public bankAccounts: BankAccounts;
    public bankTransactions: BankTransactions;
    public accounts: LendingLoanWritebackAccounts;
    public directCosts: DirectCosts;
    public payments: LendingPayments;
    public suppliers: LendingSuppliers;
    public transfers: Transfers;
    public createOperations: CreateOperations;
    private sdkConfiguration: SDKConfiguration;

    constructor(sdkConfig: SDKConfiguration) {
        this.sdkConfiguration = sdkConfig;
        this.bankAccounts = new BankAccounts(this.sdkConfiguration);
        this.bankTransactions = new BankTransactions(this.sdkConfiguration);
        this.accounts = new LendingLoanWritebackAccounts(this.sdkConfiguration);
        this.directCosts = new DirectCosts(this.sdkConfiguration);
        this.payments = new LendingPayments(this.sdkConfiguration);
        this.suppliers = new LendingSuppliers(this.sdkConfiguration);
        this.transfers = new Transfers(this.sdkConfiguration);
        this.createOperations = new CreateOperations(this.sdkConfiguration);
    }
}
