/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GetCompanyRequest = {
  /**
   * Unique identifier for a company.
   */
  companyId: string;
};

export type GetCompanyResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  company?: components.Company | undefined;
};

/** @internal */
export const GetCompanyRequest$inboundSchema: z.ZodType<
  GetCompanyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  companyId: z.string(),
});

/** @internal */
export type GetCompanyRequest$Outbound = {
  companyId: string;
};

/** @internal */
export const GetCompanyRequest$outboundSchema: z.ZodType<
  GetCompanyRequest$Outbound,
  z.ZodTypeDef,
  GetCompanyRequest
> = z.object({
  companyId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCompanyRequest$ {
  /** @deprecated use `GetCompanyRequest$inboundSchema` instead. */
  export const inboundSchema = GetCompanyRequest$inboundSchema;
  /** @deprecated use `GetCompanyRequest$outboundSchema` instead. */
  export const outboundSchema = GetCompanyRequest$outboundSchema;
  /** @deprecated use `GetCompanyRequest$Outbound` instead. */
  export type Outbound = GetCompanyRequest$Outbound;
}

/** @internal */
export const GetCompanyResponse$inboundSchema: z.ZodType<
  GetCompanyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Company: components.Company$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Company": "company",
  });
});

/** @internal */
export type GetCompanyResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  Company?: components.Company$Outbound | undefined;
};

/** @internal */
export const GetCompanyResponse$outboundSchema: z.ZodType<
  GetCompanyResponse$Outbound,
  z.ZodTypeDef,
  GetCompanyResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  company: components.Company$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    company: "Company",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCompanyResponse$ {
  /** @deprecated use `GetCompanyResponse$inboundSchema` instead. */
  export const inboundSchema = GetCompanyResponse$inboundSchema;
  /** @deprecated use `GetCompanyResponse$outboundSchema` instead. */
  export const outboundSchema = GetCompanyResponse$outboundSchema;
  /** @deprecated use `GetCompanyResponse$Outbound` instead. */
  export type Outbound = GetCompanyResponse$Outbound;
}
