/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type GetCreateChartOfAccountsModelRequest = {
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    /**
     * Unique identifier for a connection.
     */
    connectionId: string;
};

export type GetCreateChartOfAccountsModelResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    pushOption?: components.PushOption | undefined;
};

/** @internal */
export namespace GetCreateChartOfAccountsModelRequest$ {
    export type Inbound = {
        companyId: string;
        connectionId: string;
    };

    export const inboundSchema: z.ZodType<
        GetCreateChartOfAccountsModelRequest,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            companyId: z.string(),
            connectionId: z.string(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                connectionId: v.connectionId,
            };
        });

    export type Outbound = {
        companyId: string;
        connectionId: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetCreateChartOfAccountsModelRequest
    > = z
        .object({
            companyId: z.string(),
            connectionId: z.string(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                connectionId: v.connectionId,
            };
        });
}

/** @internal */
export namespace GetCreateChartOfAccountsModelResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        PushOption?: components.PushOption$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<
        GetCreateChartOfAccountsModelResponse,
        z.ZodTypeDef,
        Inbound
    > = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            PushOption: components.PushOption$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.PushOption === undefined ? null : { pushOption: v.PushOption }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        PushOption?: components.PushOption$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        GetCreateChartOfAccountsModelResponse
    > = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            pushOption: components.PushOption$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.pushOption === undefined ? null : { PushOption: v.pushOption }),
            };
        });
}
