/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type UpdateCompanyRequest = {
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    companyRequestBody?: components.CompanyRequestBody | undefined;
};

export type UpdateCompanyResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    company?: components.Company | undefined;
};

/** @internal */
export namespace UpdateCompanyRequest$ {
    export type Inbound = {
        companyId: string;
        CompanyRequestBody?: components.CompanyRequestBody$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateCompanyRequest, z.ZodTypeDef, Inbound> = z
        .object({
            companyId: z.string(),
            CompanyRequestBody: components.CompanyRequestBody$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                ...(v.CompanyRequestBody === undefined
                    ? null
                    : { companyRequestBody: v.CompanyRequestBody }),
            };
        });

    export type Outbound = {
        companyId: string;
        CompanyRequestBody?: components.CompanyRequestBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateCompanyRequest> = z
        .object({
            companyId: z.string(),
            companyRequestBody: components.CompanyRequestBody$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                ...(v.companyRequestBody === undefined
                    ? null
                    : { CompanyRequestBody: v.companyRequestBody }),
            };
        });
}

/** @internal */
export namespace UpdateCompanyResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        Company?: components.Company$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateCompanyResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Company: components.Company$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Company === undefined ? null : { company: v.Company }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Company?: components.Company$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateCompanyResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            company: components.Company$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.company === undefined ? null : { Company: v.company }),
            };
        });
}
