/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type ListCommerceLocationsRequest = {
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    /**
     * Unique identifier for a connection.
     */
    connectionId: string;
};

export type ListCommerceLocationsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * OK
     */
    commerceLocations?: components.CommerceLocations | undefined;
};

/** @internal */
export namespace ListCommerceLocationsRequest$ {
    export type Inbound = {
        companyId: string;
        connectionId: string;
    };

    export const inboundSchema: z.ZodType<ListCommerceLocationsRequest, z.ZodTypeDef, Inbound> = z
        .object({
            companyId: z.string(),
            connectionId: z.string(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                connectionId: v.connectionId,
            };
        });

    export type Outbound = {
        companyId: string;
        connectionId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListCommerceLocationsRequest> = z
        .object({
            companyId: z.string(),
            connectionId: z.string(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                connectionId: v.connectionId,
            };
        });
}

/** @internal */
export namespace ListCommerceLocationsResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        CommerceLocations?: components.CommerceLocations$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<ListCommerceLocationsResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            CommerceLocations: components.CommerceLocations$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.CommerceLocations === undefined
                    ? null
                    : { commerceLocations: v.CommerceLocations }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        CommerceLocations?: components.CommerceLocations$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListCommerceLocationsResponse> =
        z
            .object({
                httpMeta: components.HTTPMetadata$.outboundSchema,
                commerceLocations: components.CommerceLocations$.outboundSchema.optional(),
            })
            .transform((v) => {
                return {
                    HttpMeta: v.httpMeta,
                    ...(v.commerceLocations === undefined
                        ? null
                        : { CommerceLocations: v.commerceLocations }),
                };
            });
}
