/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Decimal as Decimal$ } from "../../types";
import * as z from "zod";

export type DataIntegrityByCount = {
    /**
     * The percentage of records of the type specified in the route which have a match.
     */
    matchPercentage?: Decimal$ | number | undefined;
    /**
     * The number of records of the type specified in the route which don't have a match.
     */
    unmatched?: Decimal$ | number | undefined;
    /**
     * The number of records of the type specified in the route which do have a match.
     */
    matched?: Decimal$ | number | undefined;
    /**
     * The total of unmatched and matched.
     */
    total?: Decimal$ | number | undefined;
};

/** @internal */
export namespace DataIntegrityByCount$ {
    export type Inbound = {
        matchPercentage?: number | undefined;
        unmatched?: number | undefined;
        matched?: number | undefined;
        total?: number | undefined;
    };

    export const inboundSchema: z.ZodType<DataIntegrityByCount, z.ZodTypeDef, Inbound> = z
        .object({
            matchPercentage: z
                .number()
                .transform((v) => new Decimal$(v))
                .optional(),
            unmatched: z
                .number()
                .transform((v) => new Decimal$(v))
                .optional(),
            matched: z
                .number()
                .transform((v) => new Decimal$(v))
                .optional(),
            total: z
                .number()
                .transform((v) => new Decimal$(v))
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.matchPercentage === undefined
                    ? null
                    : { matchPercentage: v.matchPercentage }),
                ...(v.unmatched === undefined ? null : { unmatched: v.unmatched }),
                ...(v.matched === undefined ? null : { matched: v.matched }),
                ...(v.total === undefined ? null : { total: v.total }),
            };
        });

    export type Outbound = {
        matchPercentage?: number | undefined;
        unmatched?: number | undefined;
        matched?: number | undefined;
        total?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DataIntegrityByCount> = z
        .object({
            matchPercentage: z
                .union([z.instanceof(Decimal$), z.number()])
                .transform((v) => (typeof v === "number" ? v : v.toNumber()))
                .optional(),
            unmatched: z
                .union([z.instanceof(Decimal$), z.number()])
                .transform((v) => (typeof v === "number" ? v : v.toNumber()))
                .optional(),
            matched: z
                .union([z.instanceof(Decimal$), z.number()])
                .transform((v) => (typeof v === "number" ? v : v.toNumber()))
                .optional(),
            total: z
                .union([z.instanceof(Decimal$), z.number()])
                .transform((v) => (typeof v === "number" ? v : v.toNumber()))
                .optional(),
        })
        .transform((v) => {
            return {
                ...(v.matchPercentage === undefined
                    ? null
                    : { matchPercentage: v.matchPercentage }),
                ...(v.unmatched === undefined ? null : { unmatched: v.unmatched }),
                ...(v.matched === undefined ? null : { matched: v.matched }),
                ...(v.total === undefined ? null : { total: v.total }),
            };
        });
}
