/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Decimal as Decimal$ } from "../../types";
import * as z from "zod";

export type WithholdingTaxItems = {
    /**
     * Name assigned to withheld tax.
     */
    name: string;
    /**
     * Amount of tax withheld.
     */
    amount: Decimal$ | number;
};

/** @internal */
export namespace WithholdingTaxItems$ {
    export type Inbound = {
        name: string;
        amount: number;
    };

    export const inboundSchema: z.ZodType<WithholdingTaxItems, z.ZodTypeDef, Inbound> = z
        .object({
            name: z.string(),
            amount: z.number().transform((v) => new Decimal$(v)),
        })
        .transform((v) => {
            return {
                name: v.name,
                amount: v.amount,
            };
        });

    export type Outbound = {
        name: string;
        amount: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WithholdingTaxItems> = z
        .object({
            name: z.string(),
            amount: z
                .union([z.instanceof(Decimal$), z.number()])
                .transform((v) => (typeof v === "number" ? v : v.toNumber())),
        })
        .transform((v) => {
            return {
                name: v.name,
                amount: v.amount,
            };
        });
}
