/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type CreateBillCreditNoteRequest = {
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    /**
     * Unique identifier for a connection.
     */
    connectionId: string;
    billCreditNote?: shared.BillCreditNote | null | undefined;
    /**
     * Time limit for the push operation to complete before it is timed out.
     */
    timeoutInMinutes?: number | undefined;
};

export type CreateBillCreditNoteResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Success
     */
    createBillCreditNoteResponse?: shared.CreateBillCreditNoteResponse | undefined;
    /**
     * The request made is not valid.
     */
    errorMessage?: shared.ErrorMessage | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace CreateBillCreditNoteRequest$ {
    export type Inbound = {
        companyId: string;
        connectionId: string;
        BillCreditNote?: shared.BillCreditNote$.Inbound | null | undefined;
        timeoutInMinutes?: number | undefined;
    };

    export const inboundSchema: z.ZodType<CreateBillCreditNoteRequest, z.ZodTypeDef, Inbound> = z
        .object({
            companyId: z.string(),
            connectionId: z.string(),
            BillCreditNote: z.nullable(shared.BillCreditNote$.inboundSchema).optional(),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                connectionId: v.connectionId,
                ...(v.BillCreditNote === undefined ? null : { billCreditNote: v.BillCreditNote }),
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });

    export type Outbound = {
        companyId: string;
        connectionId: string;
        BillCreditNote?: shared.BillCreditNote$.Outbound | null | undefined;
        timeoutInMinutes?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateBillCreditNoteRequest> = z
        .object({
            companyId: z.string(),
            connectionId: z.string(),
            billCreditNote: z.nullable(shared.BillCreditNote$.outboundSchema).optional(),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                connectionId: v.connectionId,
                ...(v.billCreditNote === undefined ? null : { BillCreditNote: v.billCreditNote }),
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });
}

/** @internal */
export namespace CreateBillCreditNoteResponse$ {
    export type Inbound = {
        ContentType: string;
        CreateBillCreditNoteResponse?: shared.CreateBillCreditNoteResponse$.Inbound | undefined;
        ErrorMessage?: shared.ErrorMessage$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<CreateBillCreditNoteResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            CreateBillCreditNoteResponse:
                shared.CreateBillCreditNoteResponse$.inboundSchema.optional(),
            ErrorMessage: shared.ErrorMessage$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.CreateBillCreditNoteResponse === undefined
                    ? null
                    : { createBillCreditNoteResponse: v.CreateBillCreditNoteResponse }),
                ...(v.ErrorMessage === undefined ? null : { errorMessage: v.ErrorMessage }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        CreateBillCreditNoteResponse?: shared.CreateBillCreditNoteResponse$.Outbound | undefined;
        ErrorMessage?: shared.ErrorMessage$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateBillCreditNoteResponse> = z
        .object({
            contentType: z.string(),
            createBillCreditNoteResponse:
                shared.CreateBillCreditNoteResponse$.outboundSchema.optional(),
            errorMessage: shared.ErrorMessage$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.createBillCreditNoteResponse === undefined
                    ? null
                    : { CreateBillCreditNoteResponse: v.createBillCreditNoteResponse }),
                ...(v.errorMessage === undefined ? null : { ErrorMessage: v.errorMessage }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
