/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type CreatePaymentRequest = {
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    /**
     * Unique identifier for a connection.
     */
    connectionId: string;
    payment?: shared.Payment | null | undefined;
    /**
     * Time limit for the push operation to complete before it is timed out.
     */
    timeoutInMinutes?: number | undefined;
};

export type CreatePaymentResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Success
     */
    createPaymentResponse?: shared.CreatePaymentResponse | undefined;
    /**
     * The request made is not valid.
     */
    errorMessage?: shared.ErrorMessage | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace CreatePaymentRequest$ {
    export type Inbound = {
        companyId: string;
        connectionId: string;
        Payment?: shared.Payment$.Inbound | null | undefined;
        timeoutInMinutes?: number | undefined;
    };

    export const inboundSchema: z.ZodType<CreatePaymentRequest, z.ZodTypeDef, Inbound> = z
        .object({
            companyId: z.string(),
            connectionId: z.string(),
            Payment: z.nullable(shared.Payment$.inboundSchema).optional(),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                connectionId: v.connectionId,
                ...(v.Payment === undefined ? null : { payment: v.Payment }),
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });

    export type Outbound = {
        companyId: string;
        connectionId: string;
        Payment?: shared.Payment$.Outbound | null | undefined;
        timeoutInMinutes?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreatePaymentRequest> = z
        .object({
            companyId: z.string(),
            connectionId: z.string(),
            payment: z.nullable(shared.Payment$.outboundSchema).optional(),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                connectionId: v.connectionId,
                ...(v.payment === undefined ? null : { Payment: v.payment }),
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });
}

/** @internal */
export namespace CreatePaymentResponse$ {
    export type Inbound = {
        ContentType: string;
        CreatePaymentResponse?: shared.CreatePaymentResponse$.Inbound | undefined;
        ErrorMessage?: shared.ErrorMessage$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<CreatePaymentResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            CreatePaymentResponse: shared.CreatePaymentResponse$.inboundSchema.optional(),
            ErrorMessage: shared.ErrorMessage$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.CreatePaymentResponse === undefined
                    ? null
                    : { createPaymentResponse: v.CreatePaymentResponse }),
                ...(v.ErrorMessage === undefined ? null : { errorMessage: v.ErrorMessage }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        CreatePaymentResponse?: shared.CreatePaymentResponse$.Outbound | undefined;
        ErrorMessage?: shared.ErrorMessage$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreatePaymentResponse> = z
        .object({
            contentType: z.string(),
            createPaymentResponse: shared.CreatePaymentResponse$.outboundSchema.optional(),
            errorMessage: shared.ErrorMessage$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.createPaymentResponse === undefined
                    ? null
                    : { CreatePaymentResponse: v.createPaymentResponse }),
                ...(v.errorMessage === undefined ? null : { ErrorMessage: v.errorMessage }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
