/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type GetInvoiceAttachmentRequest = {
    /**
     * Unique identifier for an attachment.
     */
    attachmentId: string;
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    /**
     * Unique identifier for a connection.
     */
    connectionId: string;
    /**
     * Unique identifier for an invoice.
     */
    invoiceId: string;
};

export type GetInvoiceAttachmentResponse = {
    /**
     * Success
     */
    attachment?: shared.Attachment | null | undefined;
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Your API request was not properly authorized.
     */
    errorMessage?: shared.ErrorMessage | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetInvoiceAttachmentRequest$ {
    export type Inbound = {
        attachmentId: string;
        companyId: string;
        connectionId: string;
        invoiceId: string;
    };

    export const inboundSchema: z.ZodType<GetInvoiceAttachmentRequest, z.ZodTypeDef, Inbound> = z
        .object({
            attachmentId: z.string(),
            companyId: z.string(),
            connectionId: z.string(),
            invoiceId: z.string(),
        })
        .transform((v) => {
            return {
                attachmentId: v.attachmentId,
                companyId: v.companyId,
                connectionId: v.connectionId,
                invoiceId: v.invoiceId,
            };
        });

    export type Outbound = {
        attachmentId: string;
        companyId: string;
        connectionId: string;
        invoiceId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetInvoiceAttachmentRequest> = z
        .object({
            attachmentId: z.string(),
            companyId: z.string(),
            connectionId: z.string(),
            invoiceId: z.string(),
        })
        .transform((v) => {
            return {
                attachmentId: v.attachmentId,
                companyId: v.companyId,
                connectionId: v.connectionId,
                invoiceId: v.invoiceId,
            };
        });
}

/** @internal */
export namespace GetInvoiceAttachmentResponse$ {
    export type Inbound = {
        Attachment?: shared.Attachment$.Inbound | null | undefined;
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<GetInvoiceAttachmentResponse, z.ZodTypeDef, Inbound> = z
        .object({
            Attachment: z.nullable(shared.Attachment$.inboundSchema).optional(),
            ContentType: z.string(),
            ErrorMessage: shared.ErrorMessage$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                ...(v.Attachment === undefined ? null : { attachment: v.Attachment }),
                contentType: v.ContentType,
                ...(v.ErrorMessage === undefined ? null : { errorMessage: v.ErrorMessage }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        Attachment?: shared.Attachment$.Outbound | null | undefined;
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetInvoiceAttachmentResponse> = z
        .object({
            attachment: z.nullable(shared.Attachment$.outboundSchema).optional(),
            contentType: z.string(),
            errorMessage: shared.ErrorMessage$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ...(v.attachment === undefined ? null : { Attachment: v.attachment }),
                ContentType: v.contentType,
                ...(v.errorMessage === undefined ? null : { ErrorMessage: v.errorMessage }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
