/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type GetItemRequest = {
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    /**
     * Unique identifier for an item.
     */
    itemId: string;
};

export type GetItemResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * Your API request was not properly authorized.
     */
    errorMessage?: shared.ErrorMessage | undefined;
    /**
     * Success
     */
    item?: shared.Item | null | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetItemRequest$ {
    export type Inbound = {
        companyId: string;
        itemId: string;
    };

    export const inboundSchema: z.ZodType<GetItemRequest, z.ZodTypeDef, Inbound> = z
        .object({
            companyId: z.string(),
            itemId: z.string(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                itemId: v.itemId,
            };
        });

    export type Outbound = {
        companyId: string;
        itemId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetItemRequest> = z
        .object({
            companyId: z.string(),
            itemId: z.string(),
        })
        .transform((v) => {
            return {
                companyId: v.companyId,
                itemId: v.itemId,
            };
        });
}

/** @internal */
export namespace GetItemResponse$ {
    export type Inbound = {
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Inbound | undefined;
        Item?: shared.Item$.Inbound | null | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<GetItemResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            ErrorMessage: shared.ErrorMessage$.inboundSchema.optional(),
            Item: z.nullable(shared.Item$.inboundSchema).optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.ErrorMessage === undefined ? null : { errorMessage: v.ErrorMessage }),
                ...(v.Item === undefined ? null : { item: v.Item }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Outbound | undefined;
        Item?: shared.Item$.Outbound | null | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetItemResponse> = z
        .object({
            contentType: z.string(),
            errorMessage: shared.ErrorMessage$.outboundSchema.optional(),
            item: z.nullable(shared.Item$.outboundSchema).optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.errorMessage === undefined ? null : { ErrorMessage: v.errorMessage }),
                ...(v.item === undefined ? null : { Item: v.item }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
