/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type UpdateSupplierRequest = {
    supplier?: shared.Supplier | null | undefined;
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    /**
     * Unique identifier for a connection.
     */
    connectionId: string;
    /**
     * When updating data in the destination platform Codat checks the `sourceModifiedDate` against the `lastupdated` date from the accounting platform, if they're different Codat will return an error suggesting you should initiate another pull of the data. If this is set to `true` then the update will override this check.
     */
    forceUpdate?: boolean | undefined;
    /**
     * Unique identifier for a supplier.
     */
    supplierId: string;
    /**
     * Time limit for the push operation to complete before it is timed out.
     */
    timeoutInMinutes?: number | undefined;
};

export type UpdateSupplierResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * The request made is not valid.
     */
    errorMessage?: shared.ErrorMessage | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success
     */
    updateSupplierResponse?: shared.UpdateSupplierResponse | undefined;
};

/** @internal */
export namespace UpdateSupplierRequest$ {
    export type Inbound = {
        Supplier?: shared.Supplier$.Inbound | null | undefined;
        companyId: string;
        connectionId: string;
        forceUpdate?: boolean | undefined;
        supplierId: string;
        timeoutInMinutes?: number | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateSupplierRequest, z.ZodTypeDef, Inbound> = z
        .object({
            Supplier: z.nullable(shared.Supplier$.inboundSchema).optional(),
            companyId: z.string(),
            connectionId: z.string(),
            forceUpdate: z.boolean().default(false),
            supplierId: z.string(),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.Supplier === undefined ? null : { supplier: v.Supplier }),
                companyId: v.companyId,
                connectionId: v.connectionId,
                forceUpdate: v.forceUpdate,
                supplierId: v.supplierId,
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });

    export type Outbound = {
        Supplier?: shared.Supplier$.Outbound | null | undefined;
        companyId: string;
        connectionId: string;
        forceUpdate: boolean;
        supplierId: string;
        timeoutInMinutes?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateSupplierRequest> = z
        .object({
            supplier: z.nullable(shared.Supplier$.outboundSchema).optional(),
            companyId: z.string(),
            connectionId: z.string(),
            forceUpdate: z.boolean().default(false),
            supplierId: z.string(),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.supplier === undefined ? null : { Supplier: v.supplier }),
                companyId: v.companyId,
                connectionId: v.connectionId,
                forceUpdate: v.forceUpdate,
                supplierId: v.supplierId,
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });
}

/** @internal */
export namespace UpdateSupplierResponse$ {
    export type Inbound = {
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
        UpdateSupplierResponse?: shared.UpdateSupplierResponse$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateSupplierResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            ErrorMessage: shared.ErrorMessage$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            UpdateSupplierResponse: shared.UpdateSupplierResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.ErrorMessage === undefined ? null : { errorMessage: v.ErrorMessage }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.UpdateSupplierResponse === undefined
                    ? null
                    : { updateSupplierResponse: v.UpdateSupplierResponse }),
            };
        });

    export type Outbound = {
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
        UpdateSupplierResponse?: shared.UpdateSupplierResponse$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateSupplierResponse> = z
        .object({
            contentType: z.string(),
            errorMessage: shared.ErrorMessage$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            updateSupplierResponse: shared.UpdateSupplierResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.errorMessage === undefined ? null : { ErrorMessage: v.errorMessage }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.updateSupplierResponse === undefined
                    ? null
                    : { UpdateSupplierResponse: v.updateSupplierResponse }),
            };
        });
}
