/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type UpdateCreditNoteRequest = {
    creditNote?: shared.CreditNote | null | undefined;
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    /**
     * Unique identifier for a connection.
     */
    connectionId: string;
    /**
     * Unique identifier for a credit note.
     */
    creditNoteId: string;
    /**
     * When updating data in the destination platform Codat checks the `sourceModifiedDate` against the `lastupdated` date from the accounting platform, if they're different Codat will return an error suggesting you should initiate another pull of the data. If this is set to `true` then the update will override this check.
     */
    forceUpdate?: boolean | undefined;
    /**
     * Time limit for the push operation to complete before it is timed out.
     */
    timeoutInMinutes?: number | undefined;
};

export type UpdateCreditNoteResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * The request made is not valid.
     */
    errorMessage?: shared.ErrorMessage | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success
     */
    updateCreditNoteResponse?: shared.UpdateCreditNoteResponse | undefined;
};

/** @internal */
export namespace UpdateCreditNoteRequest$ {
    export type Inbound = {
        CreditNote?: shared.CreditNote$.Inbound | null | undefined;
        companyId: string;
        connectionId: string;
        creditNoteId: string;
        forceUpdate?: boolean | undefined;
        timeoutInMinutes?: number | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateCreditNoteRequest, z.ZodTypeDef, Inbound> = z
        .object({
            CreditNote: z.nullable(shared.CreditNote$.inboundSchema).optional(),
            companyId: z.string(),
            connectionId: z.string(),
            creditNoteId: z.string(),
            forceUpdate: z.boolean().default(false),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.CreditNote === undefined ? null : { creditNote: v.CreditNote }),
                companyId: v.companyId,
                connectionId: v.connectionId,
                creditNoteId: v.creditNoteId,
                forceUpdate: v.forceUpdate,
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });

    export type Outbound = {
        CreditNote?: shared.CreditNote$.Outbound | null | undefined;
        companyId: string;
        connectionId: string;
        creditNoteId: string;
        forceUpdate: boolean;
        timeoutInMinutes?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateCreditNoteRequest> = z
        .object({
            creditNote: z.nullable(shared.CreditNote$.outboundSchema).optional(),
            companyId: z.string(),
            connectionId: z.string(),
            creditNoteId: z.string(),
            forceUpdate: z.boolean().default(false),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.creditNote === undefined ? null : { CreditNote: v.creditNote }),
                companyId: v.companyId,
                connectionId: v.connectionId,
                creditNoteId: v.creditNoteId,
                forceUpdate: v.forceUpdate,
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });
}

/** @internal */
export namespace UpdateCreditNoteResponse$ {
    export type Inbound = {
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
        UpdateCreditNoteResponse?: shared.UpdateCreditNoteResponse$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateCreditNoteResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            ErrorMessage: shared.ErrorMessage$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            UpdateCreditNoteResponse: shared.UpdateCreditNoteResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.ErrorMessage === undefined ? null : { errorMessage: v.ErrorMessage }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.UpdateCreditNoteResponse === undefined
                    ? null
                    : { updateCreditNoteResponse: v.UpdateCreditNoteResponse }),
            };
        });

    export type Outbound = {
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
        UpdateCreditNoteResponse?: shared.UpdateCreditNoteResponse$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateCreditNoteResponse> = z
        .object({
            contentType: z.string(),
            errorMessage: shared.ErrorMessage$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            updateCreditNoteResponse: shared.UpdateCreditNoteResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.errorMessage === undefined ? null : { ErrorMessage: v.errorMessage }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.updateCreditNoteResponse === undefined
                    ? null
                    : { UpdateCreditNoteResponse: v.updateCreditNoteResponse }),
            };
        });
}
