/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type UpdateInvoiceRequest = {
    invoice?: shared.Invoice | null | undefined;
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    /**
     * Unique identifier for a connection.
     */
    connectionId: string;
    /**
     * When updating data in the destination platform Codat checks the `sourceModifiedDate` against the `lastupdated` date from the accounting platform, if they're different Codat will return an error suggesting you should initiate another pull of the data. If this is set to `true` then the update will override this check.
     */
    forceUpdate?: boolean | undefined;
    /**
     * Unique identifier for an invoice.
     */
    invoiceId: string;
    /**
     * Time limit for the push operation to complete before it is timed out.
     */
    timeoutInMinutes?: number | undefined;
};

export type UpdateInvoiceResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * The request made is not valid.
     */
    errorMessage?: shared.ErrorMessage | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success
     */
    updateInvoiceResponse?: shared.UpdateInvoiceResponse | undefined;
};

/** @internal */
export namespace UpdateInvoiceRequest$ {
    export type Inbound = {
        Invoice?: shared.Invoice$.Inbound | null | undefined;
        companyId: string;
        connectionId: string;
        forceUpdate?: boolean | undefined;
        invoiceId: string;
        timeoutInMinutes?: number | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateInvoiceRequest, z.ZodTypeDef, Inbound> = z
        .object({
            Invoice: z.nullable(shared.Invoice$.inboundSchema).optional(),
            companyId: z.string(),
            connectionId: z.string(),
            forceUpdate: z.boolean().default(false),
            invoiceId: z.string(),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.Invoice === undefined ? null : { invoice: v.Invoice }),
                companyId: v.companyId,
                connectionId: v.connectionId,
                forceUpdate: v.forceUpdate,
                invoiceId: v.invoiceId,
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });

    export type Outbound = {
        Invoice?: shared.Invoice$.Outbound | null | undefined;
        companyId: string;
        connectionId: string;
        forceUpdate: boolean;
        invoiceId: string;
        timeoutInMinutes?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateInvoiceRequest> = z
        .object({
            invoice: z.nullable(shared.Invoice$.outboundSchema).optional(),
            companyId: z.string(),
            connectionId: z.string(),
            forceUpdate: z.boolean().default(false),
            invoiceId: z.string(),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.invoice === undefined ? null : { Invoice: v.invoice }),
                companyId: v.companyId,
                connectionId: v.connectionId,
                forceUpdate: v.forceUpdate,
                invoiceId: v.invoiceId,
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });
}

/** @internal */
export namespace UpdateInvoiceResponse$ {
    export type Inbound = {
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
        UpdateInvoiceResponse?: shared.UpdateInvoiceResponse$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateInvoiceResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            ErrorMessage: shared.ErrorMessage$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            UpdateInvoiceResponse: shared.UpdateInvoiceResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.ErrorMessage === undefined ? null : { errorMessage: v.ErrorMessage }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.UpdateInvoiceResponse === undefined
                    ? null
                    : { updateInvoiceResponse: v.UpdateInvoiceResponse }),
            };
        });

    export type Outbound = {
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
        UpdateInvoiceResponse?: shared.UpdateInvoiceResponse$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateInvoiceResponse> = z
        .object({
            contentType: z.string(),
            errorMessage: shared.ErrorMessage$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            updateInvoiceResponse: shared.UpdateInvoiceResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.errorMessage === undefined ? null : { ErrorMessage: v.errorMessage }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.updateInvoiceResponse === undefined
                    ? null
                    : { UpdateInvoiceResponse: v.updateInvoiceResponse }),
            };
        });
}
