/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../shared";
import * as z from "zod";

export type UpdateBankAccountRequest = {
    bankAccount?: shared.BankAccount | null | undefined;
    /**
     * Unique identifier for a bank account.
     */
    bankAccountId: string;
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    /**
     * Unique identifier for a connection.
     */
    connectionId: string;
    /**
     * When updating data in the destination platform Codat checks the `sourceModifiedDate` against the `lastupdated` date from the accounting platform, if they're different Codat will return an error suggesting you should initiate another pull of the data. If this is set to `true` then the update will override this check.
     */
    forceUpdate?: boolean | undefined;
    /**
     * Time limit for the push operation to complete before it is timed out.
     */
    timeoutInMinutes?: number | undefined;
};

export type UpdateBankAccountResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * The request made is not valid.
     */
    errorMessage?: shared.ErrorMessage | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * Success
     */
    updateBankAccountResponse?: shared.UpdateBankAccountResponse | undefined;
};

/** @internal */
export namespace UpdateBankAccountRequest$ {
    export type Inbound = {
        BankAccount?: shared.BankAccount$.Inbound | null | undefined;
        bankAccountId: string;
        companyId: string;
        connectionId: string;
        forceUpdate?: boolean | undefined;
        timeoutInMinutes?: number | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateBankAccountRequest, z.ZodTypeDef, Inbound> = z
        .object({
            BankAccount: z.nullable(shared.BankAccount$.inboundSchema).optional(),
            bankAccountId: z.string(),
            companyId: z.string(),
            connectionId: z.string(),
            forceUpdate: z.boolean().default(false),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.BankAccount === undefined ? null : { bankAccount: v.BankAccount }),
                bankAccountId: v.bankAccountId,
                companyId: v.companyId,
                connectionId: v.connectionId,
                forceUpdate: v.forceUpdate,
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });

    export type Outbound = {
        BankAccount?: shared.BankAccount$.Outbound | null | undefined;
        bankAccountId: string;
        companyId: string;
        connectionId: string;
        forceUpdate: boolean;
        timeoutInMinutes?: number | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateBankAccountRequest> = z
        .object({
            bankAccount: z.nullable(shared.BankAccount$.outboundSchema).optional(),
            bankAccountId: z.string(),
            companyId: z.string(),
            connectionId: z.string(),
            forceUpdate: z.boolean().default(false),
            timeoutInMinutes: z.number().int().optional(),
        })
        .transform((v) => {
            return {
                ...(v.bankAccount === undefined ? null : { BankAccount: v.bankAccount }),
                bankAccountId: v.bankAccountId,
                companyId: v.companyId,
                connectionId: v.connectionId,
                forceUpdate: v.forceUpdate,
                ...(v.timeoutInMinutes === undefined
                    ? null
                    : { timeoutInMinutes: v.timeoutInMinutes }),
            };
        });
}

/** @internal */
export namespace UpdateBankAccountResponse$ {
    export type Inbound = {
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
        UpdateBankAccountResponse?: shared.UpdateBankAccountResponse$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateBankAccountResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            ErrorMessage: shared.ErrorMessage$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            UpdateBankAccountResponse: shared.UpdateBankAccountResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.ErrorMessage === undefined ? null : { errorMessage: v.ErrorMessage }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
                ...(v.UpdateBankAccountResponse === undefined
                    ? null
                    : { updateBankAccountResponse: v.UpdateBankAccountResponse }),
            };
        });

    export type Outbound = {
        ContentType: string;
        ErrorMessage?: shared.ErrorMessage$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
        UpdateBankAccountResponse?: shared.UpdateBankAccountResponse$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateBankAccountResponse> = z
        .object({
            contentType: z.string(),
            errorMessage: shared.ErrorMessage$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            updateBankAccountResponse: shared.UpdateBankAccountResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.errorMessage === undefined ? null : { ErrorMessage: v.errorMessage }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
                ...(v.updateBankAccountResponse === undefined
                    ? null
                    : { UpdateBankAccountResponse: v.updateBankAccountResponse }),
            };
        });
}
