workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    accounting:
        inputs:
            - location: accounting.yaml
        registry:
            location: registry.speakeasyapi.dev/sagar-demo/sagar-demo/accounting
    lending:
        inputs:
            - location: lending.yaml
        registry:
            location: registry.speakeasyapi.dev/sagar-demo/sagar-demo/lending
targets:
    accounting-ts:
        target: typescript
        source: accounting
        output: ./accounting
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/sagar-demo/sagar-demo/accounting-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
    lending-ts:
        target: typescript
        source: lending
        output: ./lending
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/sagar-demo/sagar-demo/lending-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
