/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks";
import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import * as retries$ from "../lib/retries";
import * as schemas$ from "../lib/schemas";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as errors from "../models/errors";
import * as operations from "../models/operations";

export class Metrics extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Get commerce revenue metrics
     *
     * @remarks
     * The *Get revenue report* endpoint returns the revenue and revenue growth for a specific company connection over one or more periods of time.
     *
     * This detail helps you assess a merchant's health and advise them on performance improvement strategies. It also provides you with key insights you need to assess the credit risk of a company.
     *
     * Learn more about the formulas used to calculate the revenue metrics [here](https://docs.codat.io/lending/commerce-metrics/overview#what-metrics-are-available).
     *
     * Refer to the [commerce reporting structure](https://docs.codat.io/lending/commerce-metrics/reporting-structure) page for more details on commerce reports in Lending.
     *
     * #### Response structure
     *
     * The Revenue report's dimensions and measures are:
     *
     * | Index         | Dimensions |
     * |---------------|------------|
     * |   `index` = 0 | Period     |
     * |   `index` = 1 | Revenue    |
     *
     * | Index         | Measures                                                                                                                 |
     * |---------------|--------------------------------------------------------------------------------------------------------------------------|
     * | `index` = 0   | Value                                                                                                                    |
     * | `index` = 1   | Percentage change, defined as the change between the current and previous periods' values and expressed as a percentage. |
     *
     * The report data then combines multiple reporting dimensions and measures and outputs the value of each combination.
     *
     */
    async getRevenue(
        input: operations.GetCommerceRevenueMetricsRequest,
        options?: RequestOptions & { retries?: retries$.RetryConfig }
    ): Promise<operations.GetCommerceRevenueMetricsResponse> {
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input,
            (value$) => operations.GetCommerceRevenueMetricsRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            companyId: enc$.encodeSimple("companyId", payload$.companyId, {
                explode: false,
                charEncoding: "percent",
            }),
            connectionId: enc$.encodeSimple("connectionId", payload$.connectionId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/data/companies/{companyId}/connections/{connectionId}/assess/commerceMetrics/revenue"
        )(pathParams$);

        const query$ = [
            enc$.encodeForm("includeDisplayNames", payload$.includeDisplayNames, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("numberOfPeriods", payload$.numberOfPeriods, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("periodLength", payload$.periodLength, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("periodUnit", payload$.periodUnit, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("reportDate", payload$.reportDate, {
                explode: true,
                charEncoding: "percent",
            }),
        ]
            .filter(Boolean)
            .join("&");

        let security$;
        if (typeof this.options$.authHeader === "function") {
            security$ = { authHeader: await this.options$.authHeader() };
        } else if (this.options$.authHeader) {
            security$ = { authHeader: this.options$.authHeader };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "get-commerce-revenue-metrics",
            oAuth2Scopes: [],
            securitySource: this.options$.authHeader,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = {
            context,
            errorCodes: ["400", "401", "402", "403", "404", "429", "4XX", "500", "503", "5XX"],
        };
        const request = this.createRequest$(
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const retryConfig = options?.retries ||
            this.options$.retryConfig || {
                strategy: "backoff",
                backoff: {
                    initialInterval: 500,
                    maxInterval: 60000,
                    exponent: 1.5,
                    maxElapsedTime: 3600000,
                },
                retryConnectionErrors: true,
            };

        const response = await retries$.retry(
            () => {
                const cloned = request.clone();
                return this.do$(cloned, doOptions);
            },
            { config: retryConfig, statusCodes: ["408", "429", "5XX"] }
        );

        const responseFields$ = {
            HttpMeta: {
                Response: response,
                Request: request,
            },
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = schemas$.parse(
                responseBody,
                (val$) => {
                    return operations.GetCommerceRevenueMetricsResponse$.inboundSchema.parse({
                        ...responseFields$,
                        CommerceReport: val$,
                    });
                },
                "Response validation failed"
            );
            return result;
        } else if (
            this.matchResponse(
                response,
                [400, 401, 402, 403, 404, 429, 500, 503],
                "application/json"
            )
        ) {
            const responseBody = await response.json();
            const result = schemas$.parse(
                responseBody,
                (val$) => {
                    return errors.ErrorMessage$.inboundSchema.parse({
                        ...responseFields$,
                        ...val$,
                    });
                },
                "Response validation failed"
            );
            throw result;
        } else {
            throw new errors.SDKError("Unexpected API response", { response, request });
        }
    }

    /**
     * Get customer retention metrics
     *
     * @remarks
     * The *Get customer retention metrics* endpoint returns customer retention insights for a specific company's commerce connection over one or more periods of time.
     *
     * This detail helps you assess a merchant's health and advise them on performance improvement strategies. It also provides you with key insights you need to assess the credit risk of a company.
     *
     * #### Customer retention metrics
     *
     * - __Existing customers__: the number of unique customers that have placed an order(s) in the specified period and any previous period.
     * - __New customers__: the number of unique customers that have placed an order(s) in the specified period and none in any previous period.
     * - __Total customers__: the total number of existing and new customers within the specified period.
     * - __Retention rate__: the ratio of existing customers within the specified period compared to the total customers at the end of the previous period represented as a percentage.
     * - __Repeat rate__: the ratio of existing customers to total customers over the specified period represented as a percentage.
     *
     * Learn more about the formulas used to calculate customer retention metrics [here](https://docs.codat.io/lending/commerce-metrics/overview#what-metrics-are-available).
     *
     * #### Response structure
     *
     * The Customer retention report's dimensions and measures are:
     *
     * | Index                       | Dimensions                 |
     * |-----------------------------|----------------------------|
     * | `index` = 0                 | Period                     |
     * | `index` = 1                 | Customer retention metrics |
     *
     * | Index                | Measures    |
     * |----------------------|------------|
     * | `index` = 0          | Count      |
     * | `index` = 1          | Percentage |
     *
     * The report data then combines multiple reporting dimensions and measures and outputs the value of each combination.
     */
    async getCustomerRetention(
        input: operations.GetCommerceCustomerRetentionMetricsRequest,
        options?: RequestOptions & { retries?: retries$.RetryConfig }
    ): Promise<operations.GetCommerceCustomerRetentionMetricsResponse> {
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input,
            (value$) =>
                operations.GetCommerceCustomerRetentionMetricsRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            companyId: enc$.encodeSimple("companyId", payload$.companyId, {
                explode: false,
                charEncoding: "percent",
            }),
            connectionId: enc$.encodeSimple("connectionId", payload$.connectionId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/data/companies/{companyId}/connections/{connectionId}/assess/commerceMetrics/customerRetention"
        )(pathParams$);

        const query$ = [
            enc$.encodeForm("includeDisplayNames", payload$.includeDisplayNames, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("numberOfPeriods", payload$.numberOfPeriods, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("periodLength", payload$.periodLength, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("periodUnit", payload$.periodUnit, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("reportDate", payload$.reportDate, {
                explode: true,
                charEncoding: "percent",
            }),
        ]
            .filter(Boolean)
            .join("&");

        let security$;
        if (typeof this.options$.authHeader === "function") {
            security$ = { authHeader: await this.options$.authHeader() };
        } else if (this.options$.authHeader) {
            security$ = { authHeader: this.options$.authHeader };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "get-commerce-customer-retention-metrics",
            oAuth2Scopes: [],
            securitySource: this.options$.authHeader,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = {
            context,
            errorCodes: ["400", "401", "402", "403", "404", "429", "4XX", "500", "503", "5XX"],
        };
        const request = this.createRequest$(
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const retryConfig = options?.retries ||
            this.options$.retryConfig || {
                strategy: "backoff",
                backoff: {
                    initialInterval: 500,
                    maxInterval: 60000,
                    exponent: 1.5,
                    maxElapsedTime: 3600000,
                },
                retryConnectionErrors: true,
            };

        const response = await retries$.retry(
            () => {
                const cloned = request.clone();
                return this.do$(cloned, doOptions);
            },
            { config: retryConfig, statusCodes: ["408", "429", "5XX"] }
        );

        const responseFields$ = {
            HttpMeta: {
                Response: response,
                Request: request,
            },
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = schemas$.parse(
                responseBody,
                (val$) => {
                    return operations.GetCommerceCustomerRetentionMetricsResponse$.inboundSchema.parse(
                        {
                            ...responseFields$,
                            CommerceReport: val$,
                        }
                    );
                },
                "Response validation failed"
            );
            return result;
        } else if (
            this.matchResponse(
                response,
                [400, 401, 402, 403, 404, 429, 500, 503],
                "application/json"
            )
        ) {
            const responseBody = await response.json();
            const result = schemas$.parse(
                responseBody,
                (val$) => {
                    return errors.ErrorMessage$.inboundSchema.parse({
                        ...responseFields$,
                        ...val$,
                    });
                },
                "Response validation failed"
            );
            throw result;
        } else {
            throw new errors.SDKError("Unexpected API response", { response, request });
        }
    }

    /**
     * Get lifetime value metrics
     *
     * @remarks
     * The *Get lifetime value metrics* endpoint returns the average revenue that a specific company will generate throughout its lifespan over one or more periods of time.
     *
     * This detail helps you assess a merchant's health and advise them on performance improvement strategies. It also provides you with key insights you need to assess the credit risk of a company.
     *
     * Learn more about the formulas used to calculate the lifetime value metrics [here](https://docs.codat.io/lending/commerce-metrics/overview#what-metrics-are-available).
     *
     * Refer to the [commerce reporting structure](https://docs.codat.io/lending/commerce-metrics/reporting-structure) page for more detail on commerce reports in Lending.
     *
     * #### Response structure
     *
     * The Lifetime value report's dimensions and measures are:
     *
     * | Index         | Dimensions             |
     * |---------------|------------------------|
     * | `index` = 0   | Period                 |
     * | `index` = 1   | Lifetime value metrics |
     *
     * | Index             | Measures |
     * |-------------------|---------|
     * |   `index` = 1     | Value   |
     *
     * The report data then combines multiple reporting dimensions and measures and outputs the value of each combination.
     *
     */
    async getLifetimeValue(
        input: operations.GetCommerceLifetimeValueMetricsRequest,
        options?: RequestOptions & { retries?: retries$.RetryConfig }
    ): Promise<operations.GetCommerceLifetimeValueMetricsResponse> {
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input,
            (value$) =>
                operations.GetCommerceLifetimeValueMetricsRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            companyId: enc$.encodeSimple("companyId", payload$.companyId, {
                explode: false,
                charEncoding: "percent",
            }),
            connectionId: enc$.encodeSimple("connectionId", payload$.connectionId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent(
            "/data/companies/{companyId}/connections/{connectionId}/assess/commerceMetrics/lifetimeValue"
        )(pathParams$);

        const query$ = [
            enc$.encodeForm("includeDisplayNames", payload$.includeDisplayNames, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("numberOfPeriods", payload$.numberOfPeriods, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("periodLength", payload$.periodLength, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("periodUnit", payload$.periodUnit, {
                explode: true,
                charEncoding: "percent",
            }),
            enc$.encodeForm("reportDate", payload$.reportDate, {
                explode: true,
                charEncoding: "percent",
            }),
        ]
            .filter(Boolean)
            .join("&");

        let security$;
        if (typeof this.options$.authHeader === "function") {
            security$ = { authHeader: await this.options$.authHeader() };
        } else if (this.options$.authHeader) {
            security$ = { authHeader: this.options$.authHeader };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "get-commerce-lifetime-value-metrics",
            oAuth2Scopes: [],
            securitySource: this.options$.authHeader,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = {
            context,
            errorCodes: ["400", "401", "402", "403", "404", "429", "4XX", "500", "503", "5XX"],
        };
        const request = this.createRequest$(
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const retryConfig = options?.retries ||
            this.options$.retryConfig || {
                strategy: "backoff",
                backoff: {
                    initialInterval: 500,
                    maxInterval: 60000,
                    exponent: 1.5,
                    maxElapsedTime: 3600000,
                },
                retryConnectionErrors: true,
            };

        const response = await retries$.retry(
            () => {
                const cloned = request.clone();
                return this.do$(cloned, doOptions);
            },
            { config: retryConfig, statusCodes: ["408", "429", "5XX"] }
        );

        const responseFields$ = {
            HttpMeta: {
                Response: response,
                Request: request,
            },
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = schemas$.parse(
                responseBody,
                (val$) => {
                    return operations.GetCommerceLifetimeValueMetricsResponse$.inboundSchema.parse({
                        ...responseFields$,
                        CommerceReport: val$,
                    });
                },
                "Response validation failed"
            );
            return result;
        } else if (
            this.matchResponse(
                response,
                [400, 401, 402, 403, 404, 429, 500, 503],
                "application/json"
            )
        ) {
            const responseBody = await response.json();
            const result = schemas$.parse(
                responseBody,
                (val$) => {
                    return errors.ErrorMessage$.inboundSchema.parse({
                        ...responseFields$,
                        ...val$,
                    });
                },
                "Response validation failed"
            );
            throw result;
        } else {
            throw new errors.SDKError("Unexpected API response", { response, request });
        }
    }
}
